# THIS FILE IS AUTO-GENERATED BY THE LAYOUT TOOL. DO NOT EDIT MANUALLY.
import pygame

board_bounds = pygame.Rect(478, 35, 864, 933)
board_data = {'shape': 'rectangle'}

settings_bounds = pygame.Rect(1477, 13, 114, 114)
settings_data = {'shape': 'circle', 'center': (1534, 70), 'radius': 57}

