# THIS FILE IS AUTO-GENERATED BY THE LAYOUT TOOL. DO NOT EDIT MANUALLY.
import pygame

at_hand_1_bounds = pygame.Rect(1153,140,59,56)
at_hand_1_data = {'shape': 'rectangle'}

at_hand_2_bounds = pygame.Rect(1153,217,59,54)
at_hand_2_data = {'shape': 'rectangle'}

at_hand_3_bounds = pygame.Rect(1153,293,57,58)
at_hand_3_data = {'shape': 'rectangle'}

at_hand_4_bounds = pygame.Rect(1153,372,59,56)
at_hand_4_data = {'shape': 'rectangle'}

at_hand_5_bounds = pygame.Rect(1153,451,56,57)
at_hand_5_data = {'shape': 'rectangle'}

commit_button_bounds = pygame.Rect(1104,672,160,41)
commit_button_data = {'shape': 'rectangle'}

game_board_bounds = pygame.Rect(382,14,698,698)
game_board_data = {'shape': 'board', 'rows': 14, 'cols': 14}

settings_button_bounds = pygame.Rect(1183,8,86,86)
settings_button_data = {'shape': 'circle', 'center': (1226,51), 'radius': 43}

stage_button_bounds = pygame.Rect(1126,544,116,116)
stage_button_data = {'shape': 'circle', 'center': (1184,602), 'radius': 58}

