# THIS FILE IS AUTO-GENERATED BY THE LAYOUT TOOL. DO NOT EDIT MANUALLY.
import pygame

credits_button_bounds = pygame.Rect(767,486,350,83)
credits_button_data = {'shape': 'rectangle'}

load_button_bounds = pygame.Rect(768,233,350,87)
load_button_data = {'shape': 'rectangle'}

play_button_bounds = pygame.Rect(769,109,346,87)
play_button_data = {'shape': 'rectangle'}

quit_button_bounds = pygame.Rect(763,610,315,76)
quit_button_data = {'shape': 'rectangle'}

settings_button_bounds = pygame.Rect(769,358,351,88)
settings_button_data = {'shape': 'rectangle'}

