# THIS FILE IS AUTO-GENERATED BY THE LAYOUT TOOL. DO NOT EDIT MANUALLY.
import pygame

load_button_bounds = pygame.Rect(135,337,185,124)
load_button_data = {'shape': 'rectangle'}

play_button_bounds = pygame.Rect(135,63,293,117)
play_button_data = {'shape': 'rectangle'}

quit_button_bounds = pygame.Rect(941,438,226,226)
quit_button_data = {'shape': 'circle', 'center': (1054,551), 'radius': 113}

settings_button_bounds = pygame.Rect(810,38,282,216)
settings_button_data = {'shape': 'polygon', 'points': [(810, 161), (1042, 38), (1092, 126), (1087, 133), (866, 254), (846, 250)]}

