# THIS FILE IS AUTO-GENERATED BY THE LAYOUT TOOL. DO NOT EDIT MANUALLY.
import pygame

poly_button2_bounds = pygame.Rect(611, 508, 179, 177)
poly_button2_data = {'shape': 'polygon', 'points': [(656, 508), (790, 568), (645, 685), (611, 530)]}

polygon_button_bounds = pygame.Rect(666, 0, 757, 364)
polygon_button_data = {'shape': 'polygon', 'points': [(666, 364), (1227, 0), (1423, 219)]}

r1_bounds = pygame.Rect(479, 36, 865, 928)
r1_data = {'shape': 'rectangle'}

